const datas = [
  {
    "processingID": "1",
    "versionLevelCSLSI": "^MTBX^^inv^Xpert MTB-XDR^1^INVALID^",
    "messageDateTime": "^",
    "resultData": [
      {
        "assayNumber": "inv",
        "assayName": "Xpert MTB-XDR",
        "assayDilutionType": "1",
        "resultType": "INVALID",
        "sequenceNumber": 1,
        "result": "^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "",
        "resultStatus": "F",
        "testedBy": "Paschal Qwaray",
        "releasedBy": "",
        "analysisDateTime": "20230113124559",
        "instrumentSerial": "Cepheid-1F28376",
        "processPathID": "110012723",
        "processLaneID": "210055932"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "SPC-ahpC",
        "sequenceNumber": 2,
        "result": "NA^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^inv^^^SPC-ahpC^Ct",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "4"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "SPC-ahpC",
        "sequenceNumber": 3,
        "result": "^28.7",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX3^^inv^^^SPC-ahpC^EndPt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "5"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "SPC-ahpC",
        "sequenceNumber": 4,
        "result": "^269.0",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^inv^^^inhA^",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "6"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA",
        "sequenceNumber": 5,
        "result": "POS^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^inv^^^inhA^Ct",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "7"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA",
        "sequenceNumber": 6,
        "result": "^18.9",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^inv^^^inhA^EndPt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "8"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA",
        "sequenceNumber": 7,
        "result": "^1399.0",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^inv^^^katG^",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "9"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "katG",
        "sequenceNumber": 8,
        "result": "POS^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^inv^^^katG^Ct",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "10"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "katG",
        "sequenceNumber": 9,
        "result": "^31.5",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^inv^^^katG^EndPt",
        "analysisDateTime": "4<CR>R",
        "instrumentSerial": "11"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "katG",
        "sequenceNumber": 10,
        "result": "^132.0",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "4<CR>R",
        "resultStatus": "^MTBX^^inv^^^fabG1^",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "12"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "fabG1",
        "sequenceNumber": 11,
        "result": "POS^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^inv^^^fabG1^Ct",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "13"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "fabG1",
        "sequenceNumber": 12,
        "result": "^17.2",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^inv^^^fabG1^EndPt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "14"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "fabG1",
        "sequenceNumber": 13,
        "result": "^627.0",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^inv^^^gyrA1^",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "15"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA1",
        "sequenceNumber": 14,
        "result": "POS^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^inv^^^gyrA1^Ct",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "16"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA1",
        "sequenceNumber": 15,
        "result": "^21.7",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^inv^^^gyrA1^EndPt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "17"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA1",
        "sequenceNumber": 16,
        "result": "^311.0",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^inv^^^gyr5A2^",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "18"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyr5A2",
        "sequenceNumber": 17,
        "result": "POS^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^inv^^^gyrA2^Ct",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "19"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA2",
        "sequenceNumber": 18,
        "result": "^25.4",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^inv^^^gyrA2^EndPt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "20"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA2",
        "sequenceNumber": 19,
        "result": "^412.0",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^inv^^^gyrA3^",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "21"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA3",
        "sequenceNumber": 20,
        "result": "POS^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^inv^^^gyrA3^Ct",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "22"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA3",
        "sequenceNumber": 21,
        "result": "^22.2",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^inv^^^gyrA3^EndPt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "23"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA3",
        "sequenceNumber": 22,
        "result": "^367.0",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^inv^^^gyrB2^",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "24"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrB2",
        "sequenceNumber": 23,
        "result": "POS^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX6^^inv^^^gyrB2^Ct",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "25"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrB2",
        "sequenceNumber": 24,
        "result": "^18.9",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^inv^^^gyrB2^EndPt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "26"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrB2",
        "sequenceNumber": 25,
        "result": "^287.0",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^inv^^^rrs^",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "27"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "rrs",
        "sequenceNumber": 26,
        "result": "POS^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^inv^^^rrs^Ct",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "28"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "rrs",
        "sequenceNumber": 27,
        "result": "^16.1",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^inv^^^rrs^EndPt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "29"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "rrs",
        "sequenceNumber": 28,
        "result": "^479.0",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^inv^^^eis^",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "30"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "eis",
        "sequenceNumber": 29,
        "result": "POS^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^inv^^^eis^Ct",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "31"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "eis",
        "sequenceNumber": 30,
        "result": "^18.1",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^7MTBX^^inv^^^eis^EndPt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "32"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "eis",
        "sequenceNumber": 31,
        "result": "^110.0",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^inv^^^inhA-melt^Tm",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "33"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA-melt",
        "sequenceNumber": 32,
        "result": "^76.3",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^inv^^^inhA-melt^PkHgt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "34"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA-melt",
        "sequenceNumber": 33,
        "result": "^263.8",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^mtb^Xpert MTB-XDR^1^MTB^",
        "analysisDateTime": ""
      },
      {
        "assayNumber": "mtb",
        "assayName": "Xpert MTB-XDR",
        "assayDilutionType": "1",
        "resultType": "MTB",
        "sequenceNumber": 34,
        "result": "DETECTED^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "",
        "resultStatus": "F",
        "testedBy": "Paschal Qwaray",
        "releasedBy": "",
        "analysisDateTime": "20230113124559",
        "instrumentSerial": "Cepheid-1F28376",
        "processPathID": "1100127230",
        "processLaneID": "210055932"
      },
      {
        "assayNumber": "mtb",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA-melt",
        "sequenceNumber": 35,
        "result": "^76.3",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^mtb^^^inhA-melt^PkHgt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "37"
      },
      {
        "assayNumber": "mtb",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA-melt",
        "sequenceNumber": 36,
        "result": "^263.8",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^linh^Xpert MTB-XDR^1^Low INH Resistance^",
        "analysisDateTime": ""
      },
      {
        "assayNumber": "linh",
        "assayName": "Xpert MTB-XDR",
        "assayDilutionType": "1",
        "resultType": "Low INH Resistance",
        "sequenceNumber": 37,
        "result": "^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "",
        "resultStatus": "F",
        "testedBy": "Paschal Qwaray",
        "releasedBy": "",
        "analysisDateTime": "20230113124559",
        "instrumentSerial": "Cepheid-1F281376",
        "processPathID": "110012723",
        "processLaneID": "210055932"
      },
      {
        "assayNumber": "linh",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA-melt",
        "sequenceNumber": 38,
        "result": "^76.3",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^linh^^^inhA-melt^PkHgt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "40"
      },
      {
        "assayNumber": "linh",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA-melt",
        "sequenceNumber": 39,
        "result": "^263.8",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^linh^^^fabG1-melt^Tm",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "41"
      },
      {
        "assayNumber": "linh",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "fabG1-melt",
        "sequenceNumber": 40,
        "result": "^71.5",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^linh^^^fabG1-melt^PkHgt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "42"
      },
      {
        "assayNumber": "linh",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "fabG1-melt",
        "sequenceNumber": 41,
        "result": "^244.4",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^linh2^^^ahpC-melt^Tm",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "43"
      },
      {
        "assayNumber": "linh2",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "ahpC-melt",
        "sequenceNumber": 42,
        "result": "^68.7",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^linh^^^ahpC-melt^PkHgt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "44"
      },
      {
        "assayNumber": "linh",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "ahpC-melt",
        "sequenceNumber": 43,
        "result": "^46.4",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^linh^^^katG-mut melt^Tm",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "45"
      },
      {
        "assayNumber": "linh",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "katG-mut melt",
        "sequenceNumber": 44,
        "result": "^68.2",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^linh^^^katG-mut melt^PkHgt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "46"
      },
      {
        "assayNumber": "linh",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "katG-mut melt",
        "sequenceNumber": 45,
        "result": "^135.7",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^inh^Xpert MTB-XDR^1^INH Resistance^",
        "analysisDateTime": ""
      },
      {
        "assayNumber": "inh",
        "assayName": "Xpert MTB-XDR",
        "assayDilutionType": "1",
        "resultType": "INH Resistance",
        "sequenceNumber": 46,
        "result": "DETECTED^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "",
        "resultStatus": "F",
        "testedBy": "Paschal Qwar3ay",
        "releasedBy": "",
        "analysisDateTime": "20230113124559",
        "instrumentSerial": "Cepheid-1F28376",
        "processPathID": "110012723",
        "processLaneID": "210055932"
      },
      {
        "assayNumber": "inh",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA-melt",
        "sequenceNumber": 47,
        "result": "^76.3",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^inh^^^inhA-melt^PkHgt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "49"
      },
      {
        "assayNumber": "inh",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA-melt",
        "sequenceNumber": 48,
        "result": "^263.8",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^inh^^^fabG1-melt^Tm",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "50"
      },
      {
        "assayNumber": "inh",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "fabG1-melt",
        "sequenceNumber": 49,
        "result": "^71.5",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^inh^^^fa4bG1-melt^PkHgt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "51"
      },
      {
        "assayNumber": "inh",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "fa4bG1-melt",
        "sequenceNumber": 50,
        "result": "^244.4",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^inh^^^ahpC-melt^Tm",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "52"
      },
      {
        "assayNumber": "inh",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "ahpC-melt",
        "sequenceNumber": 51,
        "result": "^68.7",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^inh^^^ahpC-melt^PkHgt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "53"
      },
      {
        "assayNumber": "inh",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "ahpC-melt",
        "sequenceNumber": 52,
        "result": "^46.4",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^inh^^^katG-mut melt^Tm",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "54"
      },
      {
        "assayNumber": "inh",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "katG-mut melt",
        "sequenceNumber": 53,
        "result": "^68.2",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^inh^^^katG-mut melt^PkHgt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "55"
      },
      {
        "assayNumber": "inh",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "katG-mut melt",
        "sequenceNumber": 54,
        "result": "^135.7",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^lflq^Xpert MTB-XDR^1^Low FLQ5 Resistance^",
        "analysisDateTime": ""
      },
      {
        "assayNumber": "lflq",
        "assayName": "Xpert MTB-XDR",
        "assayDilutionType": "1",
        "resultType": "Low FLQ5 Resistance",
        "sequenceNumber": 55,
        "result": "DETECTED^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "",
        "resultStatus": "F",
        "testedBy": "Paschal Qwaray",
        "releasedBy": "",
        "analysisDateTime": "20230113124559",
        "instrumentSerial": "Cepheid-1F28376",
        "processPathID": "110012723",
        "processLaneID": "210055932"
      },
      {
        "assayNumber": "lflq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA-melt",
        "sequenceNumber": 56,
        "result": "^76.3",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^lflq^^^inhA-melt^PkHgt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "58"
      },
      {
        "assayNumber": "lflq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA-melt",
        "sequenceNumber": 57,
        "result": "^263.8",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^lflq^6^^gyrB2-melt^Tm",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "59"
      },
      {
        "assayNumber": "lflq",
        "assayName": "6",
        "assayDilutionType": "",
        "resultType": "gyrB2-melt",
        "sequenceNumber": 58,
        "result": "^69.5",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^lflq^^^gyrB2-melt^PkHgt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "60"
      },
      {
        "assayNumber": "lflq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrB2-melt",
        "sequenceNumber": 59,
        "result": "^76.7",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^lflq^^^gyrA1-mutB melt^Tm",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "61"
      },
      {
        "assayNumber": "lflq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA1-mutB melt",
        "sequenceNumber": 60,
        "result": "^72.1",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^lflq^^^gyrA1-mutB melt^PkHgt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "62"
      },
      {
        "assayNumber": "lflq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA1-mutB melt",
        "sequenceNumber": 61,
        "result": "^76.6",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^lflq^^^gyrA2-mutA melt^Tm",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "63"
      },
      {
        "assayNumber": "lflq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA2-mutA melt",
        "sequenceNumber": 62,
        "result": "^75.7",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^lflq^^^gyrA2-m7utA melt^PkHgt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "64"
      },
      {
        "assayNumber": "lflq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA2-m7utA melt",
        "sequenceNumber": 63,
        "result": "^112.0",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^lflq^^^gyrA3-mutB melt^Tm",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "65"
      },
      {
        "assayNumber": "lflq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA3-mutB melt",
        "sequenceNumber": 64,
        "result": "^76.6",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^lflq^^^gyrA3-mutB melt^PkHgt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "66"
      },
      {
        "assayNumber": "lflq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA3-mutB melt",
        "sequenceNumber": 65,
        "result": "^80.4",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^flq^Xpert MTB-XDR^1^FLQ Resistance^",
        "analysisDateTime": ""
      },
      {
        "assayNumber": "flq",
        "assayName": "Xpert MTB-XDR",
        "assayDilutionType": "1",
        "resultType": "FLQ Resistance",
        "sequenceNumber": 66,
        "result": "^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "",
        "resultStatus": "F",
        "testedBy": "Paschal Qwaray",
        "releasedBy": "",
        "analysisDateTime": "20230113124559",
        "instrumentSerial": "Cepheid-1F28376",
        "processPathID": "0110012723",
        "processLaneID": "210055932"
      },
      {
        "assayNumber": "flq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA-melt",
        "sequenceNumber": 67,
        "result": "^76.3",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^flq^^^inhA-melt^PkHgt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "69"
      },
      {
        "assayNumber": "flq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA-melt",
        "sequenceNumber": 68,
        "result": "^263.8",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^flq^^^gyrB2-melt^Tm",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "70"
      },
      {
        "assayNumber": "flq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrB2-melt",
        "sequenceNumber": 69,
        "result": "^69.5",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^flq^^^gyrB2-melt^PkHgt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "71"
      },
      {
        "assayNumber": "flq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrB2-melt",
        "sequenceNumber": 70,
        "result": "^76.7",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^flq^^^rrs-mel1t^Tm",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "72"
      },
      {
        "assayNumber": "flq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "rrs-mel1t",
        "sequenceNumber": 71,
        "result": "^75.0",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^flq^^^rrs-melt^PkHgt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "73"
      },
      {
        "assayNumber": "flq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "rrs-melt",
        "sequenceNumber": 72,
        "result": "^202.8",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^flq^^^eis-melt^Tm",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "74"
      },
      {
        "assayNumber": "flq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "eis-melt",
        "sequenceNumber": 73,
        "result": "^68.5",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^flq^^^eis-melt^PkHgt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "75"
      },
      {
        "assayNumber": "flq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "eis-melt",
        "sequenceNumber": 74,
        "result": "^99.4",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^flq^^^gyrA1-mutB melt^Tm",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "76"
      },
      {
        "assayNumber": "flq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA1-mutB melt",
        "sequenceNumber": 75,
        "result": "^72.1",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^flq^^^gyrA1-mutB melt^PkHgt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "77"
      },
      {
        "assayNumber": "flq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA1-mutB melt",
        "sequenceNumber": 76,
        "result": "^76.6",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^M2TBX^^flq^^^gyrA2-mutA melt^Tm",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "78"
      },
      {
        "assayNumber": "flq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA2-mutA melt",
        "sequenceNumber": 77,
        "result": "^75.7",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^flq^^^gyrA2-mutA melt^PkHgt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "79"
      },
      {
        "assayNumber": "flq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA2-mutA melt",
        "sequenceNumber": 78,
        "result": "^112.0",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^flq^^^gyrA3-mutB melt^Tm",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "80"
      },
      {
        "assayNumber": "flq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA3-mutB melt",
        "sequenceNumber": 79,
        "result": "^76.6",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^flq^^^gyrA3-mutB melt^PkHgt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "81"
      },
      {
        "assayNumber": "flq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA3-mutB melt",
        "sequenceNumber": 80,
        "result": "^80.4",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^amkr^Xpert MTB-XDR^1^AMK Resistance^",
        "analysisDateTime": ""
      },
      {
        "assayNumber": "amkr",
        "assayName": "Xpert MTB-XDR",
        "assayDilutionType": "1",
        "resultType": "AMK Resistance",
        "sequenceNumber": 81,
        "result": "NOT DET3ECTED^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "",
        "resultStatus": "F",
        "testedBy": "Paschal Qwaray",
        "releasedBy": "",
        "analysisDateTime": "20230113124559",
        "instrumentSerial": "Cepheid-1F28376",
        "processPathID": "110012723",
        "processLaneID": "210055932"
      },
      {
        "assayNumber": "amkr",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA-melt",
        "sequenceNumber": 82,
        "result": "^76.3",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^amkr^^^inhA-melt^PkHgt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "84"
      },
      {
        "assayNumber": "amkr",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA-melt",
        "sequenceNumber": 83,
        "result": "^263.8",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^amkr^^^rrs-melt^Tm",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "85"
      },
      {
        "assayNumber": "amkr",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "rrs-melt",
        "sequenceNumber": 84,
        "result": "^745.0",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^amkr^^^rrs-melt^PkHgt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "86"
      },
      {
        "assayNumber": "amkr",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "rrs-melt",
        "sequenceNumber": 85,
        "result": "^202.8",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^amkr^^^eis-melt^Tm",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "87"
      },
      {
        "assayNumber": "amkr",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "eis-melt",
        "sequenceNumber": 86,
        "result": "^68.5",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^amkr^^^eis-melt^PkHgt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "88"
      },
      {
        "assayNumber": "amkr",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "eis-melt",
        "sequenceNumber": 87,
        "result": "^99.4",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^kanr^Xpert MTB-XDR^1^KAN Resistance^",
        "analysisDateTime": ""
      },
      {
        "assayNumber": "kanr",
        "assayName": "Xpert MTB-XDR",
        "assayDilutionType": "1",
        "resultType": "KAN Resistance",
        "sequenceNumber": 88,
        "result": "NOT DETECTED^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "",
        "resultStatus": "F",
        "testedBy": "Paschal Qwaray",
        "releasedBy": "",
        "analysisDateTime": "202301513124559",
        "instrumentSerial": "Cepheid-1F28376",
        "processPathID": "110012723",
        "processLaneID": "210055932"
      },
      {
        "assayNumber": "kanr",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA-melt",
        "sequenceNumber": 89,
        "result": "^76.3",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^kanr^^^inhA-melt^PkHgt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "91"
      },
      {
        "assayNumber": "kanr",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA-melt",
        "sequenceNumber": 90,
        "result": "^263.8",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^kanr^^^rrs-melt^Tm",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "92"
      },
      {
        "assayNumber": "kanr",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "rrs-melt",
        "sequenceNumber": 91,
        "result": "^75.0",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^kanr^^^rrs-melt^PkHgt",
        "analysisDateTime": "6<CR>R",
        "instrumentSerial": "93"
      },
      {
        "assayNumber": "kanr",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "rrs-melt",
        "sequenceNumber": 92,
        "result": "^202.8",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "6<CR>R",
        "resultStatus": "^MTBX^^kanr^^^eis-melt^Tm",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "94"
      },
      {
        "assayNumber": "kanr",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "eis-melt",
        "sequenceNumber": 93,
        "result": "^68.5",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^kanr^^^eis-melt^PkHgt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "95"
      },
      {
        "assayNumber": "kanr",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "eis-melt",
        "sequenceNumber": 94,
        "result": "^99.4",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^capr^Xpert MTB-XDR^1^CAP Resistance^",
        "analysisDateTime": ""
      },
      {
        "assayNumber": "capr",
        "assayName": "Xpert MTB-XDR",
        "assayDilutionType": "1",
        "resultType": "CAP Resistance",
        "sequenceNumber": 95,
        "result": "NOT DETECTED^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "",
        "resultStatus": "F",
        "testedBy": "Paschal Qwaray",
        "releasedBy": "",
        "analysisDateTime": "20230113124559",
        "instrumentSerial": "Cepheid-1F28376",
        "processPathID": "110012723",
        "processLaneID": "210055932"
      },
      {
        "assayNumber": "capr",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA-melt",
        "sequenceNumber": 96,
        "result": "^76.3",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^capr^^^inhA-melt^PkHgt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "98"
      },
      {
        "assayNumber": "capr",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA-melt",
        "sequenceNumber": 97,
        "result": "^263.8",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^capr^^^rrs-melt^Tm",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "99"
      },
      {
        "assayNumber": "capr",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "rrs-melt",
        "sequenceNumber": 98,
        "result": "^75.0",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^capr^^^rrs-melt^PkHgt",
        "analysisDateTime": "<CR>R",
        "instrumentSerial": "100"
      },
      {
        "assayNumber": "capr",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "rrs-melt",
        "sequenceNumber": 99,
        "result": "^202.8",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "<CR>R",
        "resultStatus": "^MTBX^^ethr^Xpert MTB-XDR^1^ETH Resistance^0",
        "analysisDateTime": ""
      }
    ]
  }
]
const mapping = {
  ywRl88yte5b: ['mtb'],
  nPGTzMkULFh: ['inh', 'linh'],
  o2zbpZDZele: ['flq', 'lflq'],
  GLqRo7AuhJM: ['eth']
}

const stageMappings = {
  nPGTzMkULFh: { inh: 'INH Resistance ', linh: 'INH Resistance ' },
  ywRl88yte5b: { mtb: 'MTB ' },
  o2zbpZDZele: { flq: 'FLQ Resistance ', lflq: 'FLQ Resistance ' },
  GLqRo7AuhJM: { eth: 'ETH Resistance ' }
}

const finalResults = (results) => {
  let stage1 = []
  let stage2 = []
  Object.keys(results).forEach(dataElement => {
    if (results[dataElement].length === 2) {
      stage1 = [...stage1, { dataElement, value: stageMappings[dataElement][results[dataElement][0].assayNumber] + results[dataElement][0].result }]
      stage2 = [...stage2, { dataElement, value: stageMappings[dataElement][results[dataElement][1].assayNumber] + results[dataElement][1].result }]
    } else {
      stage1 = [...stage1, { dataElement, value: stageMappings[dataElement][results[dataElement][0].assayNumber] + results[dataElement][0].result }]
    }
  })
  return { stage1, stage2 }
}

const filterResults = (results, value) => {
  return results.find(({ assayNumber }) => assayNumber === value)?.result
}

const syncPatientResults = async (results) => {
  const result = {}
  Object.keys(mapping).forEach(key => {
    const data = mapping[key].map(d => results.find(({ assayNumber, result }) => assayNumber === d && result !== '')).filter(d => Boolean(d))
    if (data.length > 0) {
      result[key] = data
    }

  })
  return finalResults(result)
}

const sanitizeResults = async (results) => {
  results = results.map(result => {
    const cleanResult = {}
    Object.keys(result).forEach(key => {
      cleanResult[key] = isNaN(result[key]) ? (result[key] || '').replace(/^\^+|\^+$/g, '') : result[key]
    })
    return cleanResult
  })

  await syncPatientResults(results)
}
const cleanData = async () => {
  const dataArrays = datas.filter(d => d.resultData.length > 0)
  let results = []
  for (const dataArray of dataArrays) {
    const testedResults = dataArray.resultData.filter(d => d.testedBy && d.testedBy !== '')
    results = [...results, ...testedResults]
  }
  await sanitizeResults(results)
}

cleanData()
