const data = [
  {
    "senderName": "110012723 MMRC TB LAB MBEYA TANZANIA",
    "versionNumber": "GeneXpert",
    "serialNumber": "6.4",
    "processingID": "P",
    "versionLevelCSLSI": "1394-97",
    "messageDateTime": "20230223110546\nP",
    "sampleID": "120801104601-0-KK-2023-3",
    "assayNumber": "MTBX",
    "priority": "R",
    "actionCode": "",
    "resultData": []
  },
  {
    "processingID": "1",
    "versionLevelCSLSI": "^MTBX^^inv^Xpert MTB-XDR^1^INVALID^",
    "messageDateTime": "^",
    "resultData": [
      {
        "assayNumber": "inv",
        "assayName": "Xpert MTB-XDR",
        "assayDilutionType": "1",
        "resultType": "INVALID",
        "sequenceNumber": 1,
        "result": "^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "",
        "resultStatus": "F",
        "testedBy": "Paschal Qwaray",
        "releasedBy": "",
        "analysisDateTime": "20230118113607",
        "instrumentSerial": "Cepheid-1F28376",
        "processPathID": "110012723",
        "processLaneID": "210055942"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "SPC-ahpC",
        "sequenceNumber": 2,
        "result": "NA^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inv^^^SPC-ahpC^Ct",
        "analysisDateTime": "\nR",
        "instrumentSerial": "4"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "SPC-ahpC",
        "sequenceNumber": 3,
        "result": "^29.\u00172E\n\u000232",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inv^^^SPC-ahpC^EndPt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "5"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "SPC-ahpC",
        "sequenceNumber": 4,
        "result": "^250.0",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inv^^^inhA^",
        "analysisDateTime": "\nR",
        "instrumentSerial": "6"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA",
        "sequenceNumber": 5,
        "result": "POS^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inv^^^inhA^Ct",
        "analysisDateTime": "\nR",
        "instrumentSerial": "7"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA",
        "sequenceNumber": 6,
        "result": "^18.8",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inv^^^inhA^EndPt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "8"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA",
        "sequenceNumber": 7,
        "result": "^1356.0",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inv^^^katG^",
        "analysisDateTime": "\nR",
        "instrumentSerial": "9"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "katG",
        "sequenceNumber": 8,
        "result": "POS^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inv^^^katG^Ct",
        "analysisDateTime": "\nR",
        "instrumentSerial": "10"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "katG",
        "sequenceNumber": 9,
        "result": "^32.4",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inv^^^katG^E\u00172C\n\u00024ndPt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "11"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "katG",
        "sequenceNumber": 10,
        "result": "^130.0",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inv^^^fabG1^",
        "analysisDateTime": "\nR",
        "instrumentSerial": "12"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "fabG1",
        "sequenceNumber": 11,
        "result": "POS^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inv^^^fabG1^Ct",
        "analysisDateTime": "\nR",
        "instrumentSerial": "13"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "fabG1",
        "sequenceNumber": 12,
        "result": "^16.7",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inv^^^fabG1^EndPt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "14"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "fabG1",
        "sequenceNumber": 13,
        "result": "^1067.0",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inv^^^gyrA1^",
        "analysisDateTime": "\nR",
        "instrumentSerial": "15"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA1",
        "sequenceNumber": 14,
        "result": "POS^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inv^^^gyrA1^Ct",
        "analysisDateTime": "\nR",
        "instrumentSerial": "16"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA1",
        "sequenceNumber": 15,
        "result": "^22.4",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inv^^^gyrA1^EndPt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "17"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA1",
        "sequenceNumber": 16,
        "result": "^298.0",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^\u001709\n\u00025MTBX^^inv^^^gyrA2^",
        "analysisDateTime": "\nR",
        "instrumentSerial": "18"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA2",
        "sequenceNumber": 17,
        "result": "POS^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inv^^^gyrA2^Ct",
        "analysisDateTime": "\nR",
        "instrumentSerial": "19"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA2",
        "sequenceNumber": 18,
        "result": "^23.6",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inv^^^gyrA2^EndPt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "20"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA2",
        "sequenceNumber": 19,
        "result": "^482.0",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inv^^^gyrA3^",
        "analysisDateTime": "\nR",
        "instrumentSerial": "21"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA3",
        "sequenceNumber": 20,
        "result": "POS^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inv^^^gyrA3^Ct",
        "analysisDateTime": "\nR",
        "instrumentSerial": "22"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA3",
        "sequenceNumber": 21,
        "result": "^22.7",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inv^^^gyrA3^EndPt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "23"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA3",
        "sequenceNumber": 22,
        "result": "^330.0",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inv^^^gyrB2^",
        "analysisDateTime": "\nR",
        "instrumentSerial": "24"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrB2",
        "sequenceNumber": 23,
        "result": "POS\u001742\n\u00026^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inv^^^gyrB2^Ct",
        "analysisDateTime": "\nR",
        "instrumentSerial": "25"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrB2",
        "sequenceNumber": 24,
        "result": "^19.2",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inv^^^gyrB2^EndPt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "26"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrB2",
        "sequenceNumber": 25,
        "result": "^302.0",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inv^^^rrs^",
        "analysisDateTime": "\nR",
        "instrumentSerial": "27"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "rrs",
        "sequenceNumber": 26,
        "result": "POS^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inv^^^rrs^Ct",
        "analysisDateTime": "\nR",
        "instrumentSerial": "28"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "rrs",
        "sequenceNumber": 27,
        "result": "^16.0",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inv^^^rrs^EndPt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "29"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "rrs",
        "sequenceNumber": 28,
        "result": "^560.0",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inv^^^eis^",
        "analysisDateTime": "\nR",
        "instrumentSerial": "30"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "eis",
        "sequenceNumber": 29,
        "result": "POS^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inv^^^eis^Ct",
        "analysisDateTime": "\nR",
        "instrumentSerial": "31"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "eis",
        "sequenceNumber": 30,
        "result": "\u0017A9\n\u00027^18.5",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inv^^^eis^EndPt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "32"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "eis",
        "sequenceNumber": 31,
        "result": "^139.0",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inv^^^inhA-melt^Tm",
        "analysisDateTime": "\nR",
        "instrumentSerial": "33"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA-melt",
        "sequenceNumber": 32,
        "result": "^76.1",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inv^^^inhA-melt^PkHgt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "34"
      },
      {
        "assayNumber": "inv",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA-melt",
        "sequenceNumber": 33,
        "result": "^292.7",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^mtb^Xpert MTB-XDR^1^MTB^",
        "analysisDateTime": ""
      },
      {
        "assayNumber": "mtb",
        "assayName": "Xpert MTB-XDR",
        "assayDilutionType": "1",
        "resultType": "MTB",
        "sequenceNumber": 34,
        "result": "DETECTED^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "",
        "resultStatus": "F",
        "testedBy": "Paschal Qwaray",
        "releasedBy": "",
        "analysisDateTime": "20230118113607",
        "instrumentSerial": "Cepheid-1F\u001710\n\u0002028376",
        "processPathID": "110012723",
        "processLaneID": "210055942"
      },
      {
        "assayNumber": "mtb",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA-melt",
        "sequenceNumber": 35,
        "result": "^76.1",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^mtb^^^inhA-melt^PkHgt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "37"
      },
      {
        "assayNumber": "mtb",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA-melt",
        "sequenceNumber": 36,
        "result": "^292.7",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^linh^Xpert MTB-XDR^1^Low INH Resistance^",
        "analysisDateTime": ""
      },
      {
        "assayNumber": "linh",
        "assayName": "Xpert MTB-XDR",
        "assayDilutionType": "1",
        "resultType": "Low INH Resistance",
        "sequenceNumber": 37,
        "result": "^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "",
        "resultStatus": "F",
        "testedBy": "Paschal Qwaray",
        "releasedBy": "",
        "analysisDateTime": "202301181136\u0017E0\n\u0002107",
        "instrumentSerial": "Cepheid-1F28376",
        "processPathID": "110012723",
        "processLaneID": "210055942"
      },
      {
        "assayNumber": "linh",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA-melt",
        "sequenceNumber": 38,
        "result": "^76.1",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^linh^^^inhA-melt^PkHgt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "40"
      },
      {
        "assayNumber": "linh",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA-melt",
        "sequenceNumber": 39,
        "result": "^292.7",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^linh^^^fabG1-melt^Tm",
        "analysisDateTime": "\nR",
        "instrumentSerial": "41"
      },
      {
        "assayNumber": "linh",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "fabG1-melt",
        "sequenceNumber": 40,
        "result": "^71.4",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^linh^^^fabG1-melt^PkHgt",
        "analysisDateTime": "\nR\u0017CB\n\u00022",
        "instrumentSerial": "42"
      },
      {
        "assayNumber": "linh",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "fabG1-melt",
        "sequenceNumber": 41,
        "result": "^232.0",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR\u0017CB\n\u00022",
        "resultStatus": "^MTBX^^linh^^^ahpC-melt^Tm",
        "analysisDateTime": "\nR",
        "instrumentSerial": "43"
      },
      {
        "assayNumber": "linh",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "ahpC-melt",
        "sequenceNumber": 43,
        "result": "^37.5",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^linh^^^katG-mut melt^Tm",
        "analysisDateTime": "\nR",
        "instrumentSerial": "45"
      },
      {
        "assayNumber": "linh",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "katG-mut melt",
        "sequenceNumber": 44,
        "result": "^68.0",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^linh^^^katG-mut melt^PkHgt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "46"
      },
      {
        "assayNumber": "linh",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "katG-mut melt",
        "sequenceNumber": 45,
        "result": "^161.9",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inh^Xpert MTB-XDR^1^INH Resistance^",
        "analysisDateTime": ""
      },
      {
        "assayNumber": "inh",
        "assayName": "Xpert MTB-XDR",
        "assayDilutionType": "1",
        "resultType": "INH Resistance",
        "sequenceNumber": 46,
        "result": "DETECTED^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "",
        "resultStatus": "\u0017D8\n\u00023F",
        "testedBy": "Paschal Qwaray",
        "releasedBy": "",
        "analysisDateTime": "20230118113607",
        "instrumentSerial": "Cepheid-1F28376",
        "processPathID": "110012723",
        "processLaneID": "210055942"
      },
      {
        "assayNumber": "inh",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA-melt",
        "sequenceNumber": 47,
        "result": "^76.1",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inh^^^inhA-melt^PkHgt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "49"
      },
      {
        "assayNumber": "inh",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA-melt",
        "sequenceNumber": 48,
        "result": "^292.7",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inh^^^fabG1-melt^Tm",
        "analysisDateTime": "\nR",
        "instrumentSerial": "50"
      },
      {
        "assayNumber": "inh",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "fabG1-melt",
        "sequenceNumber": 49,
        "result": "^71.4",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "\u0017BC\n\u00024^MTBX^^inh^^^fabG1-melt^PkHgt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "51"
      },
      {
        "assayNumber": "inh",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "fabG1-melt",
        "sequenceNumber": 50,
        "result": "^232.0",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inh^^^ahpC-melt^Tm",
        "analysisDateTime": "\nR",
        "instrumentSerial": "52"
      },
      {
        "assayNumber": "inh",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "ahpC-melt",
        "sequenceNumber": 51,
        "result": "^68.5",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inh^^^ahpC-melt^PkHgt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "53"
      },
      {
        "assayNumber": "inh",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "ahpC-melt",
        "sequenceNumber": 52,
        "result": "^37.5",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inh^^^katG-mut melt^Tm",
        "analysisDateTime": "\nR",
        "instrumentSerial": "54"
      },
      {
        "assayNumber": "inh",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "katG-mut melt",
        "sequenceNumber": 53,
        "result": "^68.0",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^inh^^^katG-mut melt^PkHgt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "55"
      },
      {
        "assayNumber": "inh",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "katG-mut melt",
        "sequenceNumber": 54,
        "result": "^161.9",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^lflq^Xpert MT\u001766\n\u00025B-XDR^1^Low FLQ Resistance^",
        "analysisDateTime": ""
      },
      {
        "assayNumber": "lflq",
        "assayName": "Xpert MT\u001766\n\u00025B-XDR",
        "assayDilutionType": "1",
        "resultType": "Low FLQ Resistance",
        "sequenceNumber": 55,
        "result": "DETECTED^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "",
        "resultStatus": "F",
        "testedBy": "Paschal Qwaray",
        "releasedBy": "",
        "analysisDateTime": "20230118113607",
        "instrumentSerial": "Cepheid-1F28376",
        "processPathID": "110012723",
        "processLaneID": "210055942"
      },
      {
        "assayNumber": "lflq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA-melt",
        "sequenceNumber": 56,
        "result": "^76.1",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^lflq^^^inhA-melt^PkHgt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "\u00172A\n\u0002658"
      },
      {
        "assayNumber": "lflq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA-melt",
        "sequenceNumber": 57,
        "result": "^292.7",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^lflq^^^gyrB2-melt^Tm",
        "analysisDateTime": "\nR",
        "instrumentSerial": "59"
      },
      {
        "assayNumber": "lflq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrB2-melt",
        "sequenceNumber": 59,
        "result": "^85.7",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^lflq^^^gyrA1-mutB melt^Tm",
        "analysisDateTime": "\nR",
        "instrumentSerial": "61"
      },
      {
        "assayNumber": "lflq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA1-mutB melt",
        "sequenceNumber": 60,
        "result": "^71.9",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^lflq^^^gyrA1-mutB melt^PkHgt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "62"
      },
      {
        "assayNumber": "lflq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA1-mutB melt",
        "sequenceNumber": 61,
        "result": "^92.7",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^lflq^^^gyrA2-mutA melt^Tm",
        "analysisDateTime": "\nR",
        "instrumentSerial": "63"
      },
      {
        "assayNumber": "lflq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA2-mutA melt",
        "sequenceNumber": 62,
        "result": "^75.7",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^\u00174A\n\u00027^lflq^^^gyrA2-mutA melt^PkHgt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "64"
      },
      {
        "assayNumber": "lflq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA2-mutA melt",
        "sequenceNumber": 63,
        "result": "^159.9",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^lflq^^^gyrA3-mutB melt^Tm",
        "analysisDateTime": "\nR",
        "instrumentSerial": "65"
      },
      {
        "assayNumber": "lflq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA3-mutB melt",
        "sequenceNumber": 64,
        "result": "^76.4",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^lflq^^^gyrA3-mutB melt^PkHgt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "66"
      },
      {
        "assayNumber": "lflq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA3-mutB melt",
        "sequenceNumber": 65,
        "result": "^96.6",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^flq^Xpert MTB-XDR^1^FLQ Resistance^",
        "analysisDateTime": ""
      },
      {
        "assayNumber": "flq",
        "assayName": "Xpert MTB-XDR",
        "assayDilutionType": "1",
        "resultType": "FLQ Resistance",
        "sequenceNumber": 66,
        "result": "^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "",
        "resultStatus": "F",
        "testedBy": "Paschal Qwaray",
        "releasedBy": "",
        "analysisDateTime": "20230118113607",
        "instrumentSerial": "C\u0017C9\n\u00020epheid-1F28376",
        "processPathID": "110012723",
        "processLaneID": "210055942"
      },
      {
        "assayNumber": "flq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA-melt",
        "sequenceNumber": 67,
        "result": "^76.1",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^flq^^^inhA-melt^PkHgt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "69"
      },
      {
        "assayNumber": "flq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA-melt",
        "sequenceNumber": 68,
        "result": "^292.7",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^flq^^^gyrB2-melt^Tm",
        "analysisDateTime": "\nR",
        "instrumentSerial": "70"
      },
      {
        "assayNumber": "flq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrB2-melt",
        "sequenceNumber": 69,
        "result": "^69.3",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^flq^^^gyrB2-melt^PkHgt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "71"
      },
      {
        "assayNumber": "flq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrB2-melt",
        "sequenceNumber": 70,
        "result": "^85.7",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX\u00173B\n\u00021^^flq^^^rrs-melt^Tm",
        "analysisDateTime": "\nR",
        "instrumentSerial": "72"
      },
      {
        "assayNumber": "flq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "rrs-melt",
        "sequenceNumber": 71,
        "result": "^74.8",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^flq^^^rrs-melt^PkHgt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "73"
      },
      {
        "assayNumber": "flq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "rrs-melt",
        "sequenceNumber": 72,
        "result": "^217.3",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^flq^^^eis-melt^Tm",
        "analysisDateTime": "\nR",
        "instrumentSerial": "74"
      },
      {
        "assayNumber": "flq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "eis-melt",
        "sequenceNumber": 73,
        "result": "^68.4",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^flq^^^eis-melt^PkHgt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "75"
      },
      {
        "assayNumber": "flq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "eis-melt",
        "sequenceNumber": 74,
        "result": "^95.0",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^flq^^^gyrA1-mutB melt^Tm",
        "analysisDateTime": "\nR",
        "instrumentSerial": "76"
      },
      {
        "assayNumber": "flq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA1-mutB melt",
        "sequenceNumber": 75,
        "result": "^71.9",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^flq^^^gyrA1-mutB melt^PkHgt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "77"
      },
      {
        "assayNumber": "flq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA1-mutB melt",
        "sequenceNumber": 76,
        "result": "^\u0017AF\n\u0002292.7",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^flq^^^gyrA2-mutA melt^Tm",
        "analysisDateTime": "\nR",
        "instrumentSerial": "78"
      },
      {
        "assayNumber": "flq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA2-mutA melt",
        "sequenceNumber": 77,
        "result": "^75.7",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^flq^^^gyrA2-mutA melt^PkHgt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "79"
      },
      {
        "assayNumber": "flq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA2-mutA melt",
        "sequenceNumber": 78,
        "result": "^159.9",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^flq^^^gyrA3-mutB melt^Tm",
        "analysisDateTime": "\nR",
        "instrumentSerial": "80"
      },
      {
        "assayNumber": "flq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA3-mutB melt",
        "sequenceNumber": 79,
        "result": "^76.4",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^flq^^^gyrA3-mutB melt^PkHgt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "81"
      },
      {
        "assayNumber": "flq",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "gyrA3-mutB melt",
        "sequenceNumber": 80,
        "result": "^96.6",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^amkr^Xpert MTB-XDR^1^AMK Resi\u001705\n\u00023stance^",
        "analysisDateTime": ""
      },
      {
        "assayNumber": "amkr",
        "assayName": "Xpert MTB-XDR",
        "assayDilutionType": "1",
        "resultType": "AMK Resi\u001705\n\u00023stance",
        "sequenceNumber": 81,
        "result": "NOT DETECTED^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "",
        "resultStatus": "F",
        "testedBy": "Paschal Qwaray",
        "releasedBy": "",
        "analysisDateTime": "20230118113607",
        "instrumentSerial": "Cepheid-1F28376",
        "processPathID": "110012723",
        "processLaneID": "210055942"
      },
      {
        "assayNumber": "amkr",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA-melt",
        "sequenceNumber": 82,
        "result": "^76.1",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^amkr^^^inhA-melt^PkHgt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "84"
      },
      {
        "assayNumber": "amkr",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA-melt",
        "sequenceNumber": 83,
        "result": "^292.7",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^amkr^^\u0017A1\n\u00024^rrs-melt^Tm",
        "analysisDateTime": "\nR",
        "instrumentSerial": "85"
      },
      {
        "assayNumber": "amkr",
        "assayName": "",
        "assayDilutionType": "\u0017A1\n\u00024",
        "resultType": "rrs-melt",
        "sequenceNumber": 84,
        "result": "^74.8",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^amkr^^^rrs-melt^PkHgt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "86"
      },
      {
        "assayNumber": "amkr",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "rrs-melt",
        "sequenceNumber": 85,
        "result": "^217.3",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^amkr^^^eis-melt^Tm",
        "analysisDateTime": "\nR",
        "instrumentSerial": "87"
      },
      {
        "assayNumber": "amkr",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "eis-melt",
        "sequenceNumber": 86,
        "result": "^68.4",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^amkr^^^eis-melt^PkHgt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "88"
      },
      {
        "assayNumber": "amkr",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "eis-melt",
        "sequenceNumber": 87,
        "result": "^95.0",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^kanr^Xpert MTB-XDR^1^KAN Resistance^",
        "analysisDateTime": ""
      },
      {
        "assayNumber": "kanr",
        "assayName": "Xpert MTB-XDR",
        "assayDilutionType": "1",
        "resultType": "KAN Resistance",
        "sequenceNumber": 88,
        "result": "NOT DETECTED^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "",
        "resultStatus": "F",
        "testedBy": "Paschal Qwaray",
        "releasedBy": "",
        "analysisDateTime": "20230118113607",
        "instrumentSerial": "Cepheid-1F28376",
        "processPathID": "110012723",
        "processLaneID": "210055942"
      },
      {
        "assayNumber": "kanr",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA-melt",
        "sequenceNumber": 89,
        "result": "^76.1",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^kanr^^^inhA-melt^PkHgt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "91"
      },
      {
        "assayNumber": "kanr",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA-melt",
        "sequenceNumber": 90,
        "result": "^292.7",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^kanr^^^rrs-melt^Tm",
        "analysisDateTime": "\nR",
        "instrumentSerial": "92"
      },
      {
        "assayNumber": "kanr",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "rrs-melt",
        "sequenceNumber": 91,
        "result": "^74.8",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^kanr^^^rrs-melt^\u001744\n\u00026PkHgt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "93"
      },
      {
        "assayNumber": "kanr",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "rrs-melt",
        "sequenceNumber": 92,
        "result": "^217.3",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^kanr^^^eis-melt^Tm",
        "analysisDateTime": "\nR",
        "instrumentSerial": "94"
      },
      {
        "assayNumber": "kanr",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "eis-melt",
        "sequenceNumber": 93,
        "result": "^68.4",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^kanr^^^eis-melt^PkHgt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "95"
      },
      {
        "assayNumber": "kanr",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "eis-melt",
        "sequenceNumber": 94,
        "result": "^95.0",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^capr^Xpert MTB-XDR^1^CAP Resistance^",
        "analysisDateTime": ""
      },
      {
        "assayNumber": "capr",
        "assayName": "Xpert MTB-XDR",
        "assayDilutionType": "1",
        "resultType": "CAP Resistance",
        "sequenceNumber": 95,
        "result": "NOT DETECTED^",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "",
        "resultStatus": "F",
        "testedBy": "Paschal Qwaray",
        "releasedBy": "",
        "analysisDateTime": "20230118113607",
        "instrumentSerial": "Cepheid-1F28376",
        "processPathID": "110012723",
        "processLaneID": "\u00179E\n\u00027210055942"
      },
      {
        "assayNumber": "capr",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA-melt",
        "sequenceNumber": 96,
        "result": "^76.1",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^capr^^^inhA-melt^PkHgt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "98"
      },
      {
        "assayNumber": "capr",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "inhA-melt",
        "sequenceNumber": 97,
        "result": "^292.7",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^capr^^^rrs-melt^Tm",
        "analysisDateTime": "\nR",
        "instrumentSerial": "99"
      },
      {
        "assayNumber": "capr",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "rrs-melt",
        "sequenceNumber": 98,
        "result": "^74.8",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^capr^^^rrs-melt^PkHgt",
        "analysisDateTime": "\nR",
        "instrumentSerial": "100"
      },
      {
        "assayNumber": "capr",
        "assayName": "",
        "assayDilutionType": "",
        "resultType": "rrs-melt",
        "sequenceNumber": 99,
        "result": "^217.3",
        "unit": "",
        "referenceRange": "",
        "abnormalFlag": "\nR",
        "resultStatus": "^MTBX^^ethr^Xpert MTB-XDR^1^\u0017A5\n\u00020ETH Resistance^",
        "analysisDateTime": ""
      }
    ]
  }
]

const syncPatientResults = async (results) => {

}

const sanitizeResults = async (results) => {
  results = results.map(result => {
    const cleanResult = {}
    Object.keys(result).forEach(key => {
      cleanResult[key] = isNaN(result[key]) ? (result[key] || '').replace(/^\^+|\^+$/g, '') : result[key]
    })
    return cleanResult
  })

  await syncPatientResults(results)
}
const cleanData = async () => {
  const dataArrays = data.filter(d => d.resultData.length > 0)
  let results = []
  for (const dataArray of dataArrays) {
    const testedResults = dataArray.resultData.filter(d => d.testedBy && d.testedBy !== '')
    results = [...results, ...testedResults]
  }
  await sanitizeResults(results)
}

cleanData()
