// Copyright 2023 UDSM DHIS2 Lab All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

--
-- PostgreSQL database dump
--

-- Dumped from database version 14.6 (Homebrew)
-- Dumped by pg_dump version 14.6 (Homebrew)

-- Started on 2022-12-14 12:53:30 EAT

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 214 (class 1259 OID 16574)
-- Name: app_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.app_log (
    id integer NOT NULL,
    log text NOT NULL,
    added_on timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.app_log OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16618)
-- Name: app_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.app_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.app_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 209 (class 1259 OID 16466)
-- Name: fx; Type: TABLE; Schema: public; Owner: bennett
--

CREATE TABLE public.fx (
    id integer NOT NULL,
    code text,
    name text,
    description text,
    frequency text
);


ALTER TABLE public.fx OWNER TO bennett;

--
-- TOC entry 216 (class 1259 OID 16580)
-- Name: orders; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.orders (
    id integer NOT NULL,
    order_id text NOT NULL,
    test_id text,
    test_type text NOT NULL,
    created_date date,
    test_unit text,
    results text,
    tested_by text,
    analysed_date_time timestamp without time zone,
    specimen_date_time timestamp without time zone,
    authorised_date_time timestamp without time zone,
    result_accepted_date_time timestamp without time zone,
    machine_used text,
    test_location text,
    created_at integer DEFAULT 0 NOT NULL,
    result_status integer DEFAULT 0 NOT NULL,
    lims_sync_status integer DEFAULT 0,
    lims_sync_date_time timestamp without time zone,
    repeated integer DEFAULT 0,
    test_description text,
    is_printed integer,
    printed_at integer,
    raw_text text,
    added_on timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.orders OWNER TO postgres;

--
-- TOC entry 218 (class 1259 OID 16605)
-- Name: orders_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.orders_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 211 (class 1259 OID 16474)
-- Name: process; Type: TABLE; Schema: public; Owner: bennett
--

CREATE TABLE public.process (
    id integer NOT NULL,
    code text,
    name text,
    description text,
    frequency text,
    secret_id integer
);


ALTER TABLE public.process OWNER TO bennett;

--
-- TOC entry 210 (class 1259 OID 16473)
-- Name: process_id_seq; Type: SEQUENCE; Schema: public; Owner: bennett
--

CREATE SEQUENCE public.process_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.process_id_seq OWNER TO bennett;

--
-- TOC entry 3624 (class 0 OID 0)
-- Dependencies: 210
-- Name: process_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: bennett
--

ALTER SEQUENCE public.process_id_seq OWNED BY public.process.id;


--
-- TOC entry 215 (class 1259 OID 16579)
-- Name: raw_data; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.raw_data (
    id integer NOT NULL,
    data text NOT NULL,
    machine text NOT NULL,
    added_on timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.raw_data OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 16600)
-- Name: raw_data_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.raw_data ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.raw_data_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 213 (class 1259 OID 16489)
-- Name: secret; Type: TABLE; Schema: public; Owner: bennett
--

CREATE TABLE public.secret (
    id integer NOT NULL,
    name text NOT NULL,
    description text,
    value json NOT NULL
);


ALTER TABLE public.secret OWNER TO bennett;

--
-- TOC entry 212 (class 1259 OID 16488)
-- Name: secret_id_seq; Type: SEQUENCE; Schema: public; Owner: bennett
--

CREATE SEQUENCE public.secret_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.secret_id_seq OWNER TO bennett;

--
-- TOC entry 3627 (class 0 OID 0)
-- Dependencies: 212
-- Name: secret_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: bennett
--

ALTER SEQUENCE public.secret_id_seq OWNED BY public.secret.id;


--
-- TOC entry 3457 (class 2604 OID 16477)
-- Name: process id; Type: DEFAULT; Schema: public; Owner: bennett
--

ALTER TABLE ONLY public.process ALTER COLUMN id SET DEFAULT nextval('public.process_id_seq'::regclass);


--
-- TOC entry 3458 (class 2604 OID 16492)
-- Name: secret id; Type: DEFAULT; Schema: public; Owner: bennett
--

ALTER TABLE ONLY public.secret ALTER COLUMN id SET DEFAULT nextval('public.secret_id_seq'::regclass);


--
-- TOC entry 3472 (class 2606 OID 16620)
-- Name: app_log app_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.app_log
    ADD CONSTRAINT app_log_pkey PRIMARY KEY (id);


--
-- TOC entry 3467 (class 2606 OID 16472)
-- Name: fx fx_pkey; Type: CONSTRAINT; Schema: public; Owner: bennett
--

ALTER TABLE ONLY public.fx
    ADD CONSTRAINT fx_pkey PRIMARY KEY (id);


--
-- TOC entry 3476 (class 2606 OID 16608)
-- Name: orders orders_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.orders
    ADD CONSTRAINT orders_pkey PRIMARY KEY (id);


--
-- TOC entry 3474 (class 2606 OID 16606)
-- Name: raw_data raw_data_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.raw_data
    ADD CONSTRAINT raw_data_pkey PRIMARY KEY (id);


--
-- TOC entry 3470 (class 2606 OID 16496)
-- Name: secret secret_pkey; Type: CONSTRAINT; Schema: public; Owner: bennett
--

ALTER TABLE ONLY public.secret
    ADD CONSTRAINT secret_pkey PRIMARY KEY (id);


--
-- TOC entry 3468 (class 1259 OID 16497)
-- Name: primary_key; Type: INDEX; Schema: public; Owner: bennett
--

CREATE INDEX primary_key ON public.secret USING btree (id);


--
-- TOC entry 3477 (class 2606 OID 16498)
-- Name: process fk_secrets; Type: FK CONSTRAINT; Schema: public; Owner: bennett
--

ALTER TABLE ONLY public.process
    ADD CONSTRAINT fk_secrets FOREIGN KEY (secret_id) REFERENCES public.secret(id);


--
-- TOC entry 3622 (class 0 OID 0)
-- Dependencies: 209
-- Name: TABLE fx; Type: ACL; Schema: public; Owner: bennett
--

GRANT ALL ON TABLE public.fx TO postgres;


--
-- TOC entry 3623 (class 0 OID 0)
-- Dependencies: 211
-- Name: TABLE process; Type: ACL; Schema: public; Owner: bennett
--

GRANT ALL ON TABLE public.process TO postgres;


--
-- TOC entry 3625 (class 0 OID 0)
-- Dependencies: 210
-- Name: SEQUENCE process_id_seq; Type: ACL; Schema: public; Owner: bennett
--

GRANT ALL ON SEQUENCE public.process_id_seq TO postgres;


--
-- TOC entry 3626 (class 0 OID 0)
-- Dependencies: 213
-- Name: TABLE secret; Type: ACL; Schema: public; Owner: bennett
--

GRANT ALL ON TABLE public.secret TO postgres;


--
-- TOC entry 3628 (class 0 OID 0)
-- Dependencies: 212
-- Name: SEQUENCE secret_id_seq; Type: ACL; Schema: public; Owner: bennett
--

GRANT ALL ON SEQUENCE public.secret_id_seq TO postgres;


-- Completed on 2022-12-14 12:53:30 EAT

--
-- PostgreSQL database dump complete
--

